use std::collections::HashMap;

use once_cell::sync::Lazy;

macro_rules! css_properties {
    ( $(V ( $key:ident, $name:expr, $default: expr ) ),* ) => {
        fn get_css_property_map()->HashMap<String,u32>{
            let mut temp = HashMap::new();
            let mut i:u32 = 0;
            $(
                i+=1;
                temp.insert($name.into(),i);
            )*
            temp
        }
    };
}

pub static CSS_PROPERTY_MAP: Lazy<HashMap<String, u32>> = Lazy::new(|| get_css_property_map());

css_properties!(
  V(Top, "top", "auto"),
  V(Left, "left", "auto"),
  V(Right, "right", "auto"),
  V(Bottom, "bottom", "auto"),
  V(Position, "position", "relative"),
  V(BoxSizing, "box-sizing", "auto"),
  V(BackgroundColor, "background-color", "transparent"),
  V(BorderLeftColor, "border-left-color", "black"),
  V(BorderRightColor, "border-right-color", "black"),
  V(BorderTopColor, "border-top-color", "black"),
  V(BorderBottomColor, "border-bottom-color", "black"),
  V(BorderRadius, "border-radius", "0px"),
  V(BorderTopLeftRadius, "border-top-left-radius", "0px"),
  V(BorderBottomLeftRadius, "border-bottom-left-radius", "0px"),
  V(BorderTopRightRadius, "border-top-right-radius", "0px"),
  V(BorderBottomRightRadius, "border-bottom-right-radius", "0px"),
  V(BorderWidth, "border-width", "0px"),
  V(BorderLeftWidth, "border-left-width", "0px"),
  V(BorderRightWidth, "border-right-width", "0px"),
  V(BorderTopWidth, "border-top-width", "0px"),
  V(BorderBottomWidth, "border-bottom-width", "0px"),
  V(Color, "color", "black"),
  V(Opacity, "opacity", "1"),
  V(Display, "display", "auto"),
  V(Overflow, "overflow", "hidden"),
  V(Height, "height", "auto"),
  V(Width, "width", "auto"),
  V(MaxWidth, "max-width", "auto"),
  V(MinWidth, "min-width", "auto"),
  V(MaxHeight, "max-height", "auto"),
  V(MinHeight, "min-height", "auto"),
  V(Padding, "padding", "0px"),
  V(PaddingLeft, "padding-left", "0px"),
  V(PaddingRight, "padding-right", "0px"),
  V(PaddingTop, "padding-top", "0px"),
  V(PaddingBottom, "padding-bottom", "0px"),
  V(Margin, "margin", "0px"),
  V(MarginLeft, "margin-left", "0px"),
  V(MarginRight, "margin-right", "0px"),
  V(MarginTop, "margin-top", "0px"),
  V(MarginBottom, "margin-bottom", "0px"),
  V(WhiteSpace, "white-space", "normal"),
  V(LetterSpacing, "letter-spacing", "0px"),
  V(TextAlign, "text-align", "start"),
  V(LineHeight, "line-height", ""),
  V(TextOverflow, "text-overflow", "clip"),
  V(FontSize, "font-size", "medium"),
  V(FontWeight, "font-weight", "normal"),
  V(Flex, "flex", "0"),
  V(FlexGrow, "flex-grow", "0"),
  V(FlexShrink, "flex-shrink", "1"),
  V(FlexBasis, "flex-basis", "auto"),
  V(FlexDirection, "flex-direction", "row"),
  V(FlexWrap, "flex-wrap", "nowrap"),
  V(AlignItems, "align-items", "stretch"),
  V(AlignSelf, "align-self", "stretch"),
  V(AlignContent, "align-content", "stretch"),
  V(JustifyContent, "justify-content", "stretch"),
  V(Background, "background", "transparent, transparent"),
  V(BorderColor, "border-color", "black"),
  V(FontFamily, "font-family", ""),
  V(FontStyle, "font-style", "normal"),
  V(Transform, "transform", ""),
  V(Animation, "animation", ""),
  V(AnimationName, "animation-name", ""),
  V(AnimationDuration, "animation-duration", ""),
  V(
    AnimationTimingFunction,
    "animation-timing-function",
    "linear"
  ),
  V(AnimationDelay, "animation-delay", "0s"),
  V(AnimationIterationCount, "animation-iteration-count", "1"),
  V(AnimationDirection, "animation-direction", "normal"),
  V(AnimationFillMode, "animation-fill-mode", "none"),
  V(AnimationPlayState, "animation-play-state", "running"),
  V(LineSpacing, "line-spacing", "0px"),
  V(BorderStyle, "border-style", "solid"),
  V(Order, "order", "0"),
  V(BoxShadow, "box-shadow", ""),
  V(TransformOrigin, "transform-origin", ""),
  V(LinearOrientation, "linear-orientation", "vertical"),
  V(LinearWeightSum, "linear-weight-sum", "0"),
  V(LinearWeight, "linear-weight", "0"),
  V(LinearGravity, "linear-gravity", "none"),
  V(LinearLayoutGravity, "linear-layout-gravity", "none"),
  V(
    LayoutAnimationCreateDuration,
    "layout-animation-create-duration",
    "0s"
  ),
  V(
    LayoutAnimationCreateTimingFunction,
    "layout-animation-create-timing-function",
    "linear"
  ),
  V(
    LayoutAnimationCreateDelay,
    "layout-animation-create-delay",
    "0s"
  ),
  V(
    LayoutAnimationCreateProperty,
    "layout-animation-create-property",
    "opacity"
  ),
  V(
    LayoutAnimationDeleteDuration,
    "layout-animation-delete-duration",
    "0s"
  ),
  V(
    LayoutAnimationDeleteTimingFunction,
    "layout-animation-delete-timing-function",
    "linear"
  ),
  V(
    LayoutAnimationDeleteDelay,
    "layout-animation-delete-delay",
    "0s"
  ),
  V(
    LayoutAnimationDeleteProperty,
    "layout-animation-delete-property",
    "opacity"
  ),
  V(
    LayoutAnimationUpdateDuration,
    "layout-animation-update-duration",
    "0s"
  ),
  V(
    LayoutAnimationUpdateTimingFunction,
    "layout-animation-update-timing-function",
    "linear"
  ),
  V(
    LayoutAnimationUpdateDelay,
    "layout-animation-update-delay",
    "0s"
  ),
  V(AdaptFontSize, "adapt-font-size", "0"),
  V(AspectRatio, "aspect-ratio", ""),
  V(TextDecoration, "text-decoration", ""),
  V(TextShadow, "text-shadow", ""),
  V(BackgroundImage, "background-image", ""),
  V(BackgroundPosition, "background-position", ""),
  V(BackgroundOrigin, "background-origin", "border-box"),
  V(BackgroundRepeat, "background-repeat", "no-repeat"),
  V(BackgroundSize, "background-size", ""),
  V(Border, "border", ""),
  V(Visibility, "visibility", "visible"),
  V(BorderRight, "border-right", ""),
  V(BorderLeft, "border-left", ""),
  V(BorderTop, "border-top", ""),
  V(BorderBottom, "border-bottom", ""),
  V(Transition, "transition", ""),
  V(TransitionProperty, "transition-property", ""),
  V(TransitionDuration, "transition-duration", ""),
  V(TransitionDelay, "transition-delay", ""),
  V(TransitionTimingFunction, "transition-timing-function", ""),
  V(Content, "content", ""),
  V(BorderLeftStyle, "border-left-style", ""),
  V(BorderRightStyle, "border-right-style", ""),
  V(BorderTopStyle, "border-top-style", ""),
  V(BorderBottomStyle, "border-bottom-style", ""),
  V(ImplicitAnimation, "implicit-animation", "true"),
  V(OverflowX, "overflow-x", "hidden"),
  V(OverflowY, "overflow-y", "hidden"),
  V(WordBreak, "word-break", "normal"),
  V(BackgroundClip, "background-clip", "border-box"),
  V(Outline, "outline", "medium none black"),
  V(OutlineColor, "outline-color", "black"),
  V(OutlineStyle, "outline-style", "black"),
  V(OutlineWidth, "outline-width", "medium"),
  V(VerticalAlign, "vertical-align", "default"),
  V(CaretColor, "caret-color", "auto"),
  V(Direction, "direction", "normal"),
  V(RelativeId, "relative-id", "-1"),
  V(RelativeAlignTop, "relative-align-top", "-1"),
  V(RelativeAlignRight, "relative-align-right", "-1"),
  V(RelativeAlignBottom, "relative-align-bottom", "-1"),
  V(RelativeAlignLeft, "relative-align-left", "-1"),
  V(RelativeTopOf, "relative-top-of", "-1"),
  V(RelativeRightOf, "relative-right-of", "-1"),
  V(RelativeBottomOf, "relative-bottom-of", "-1"),
  V(RelativeLeftOf, "relative-left-of", "-1"),
  V(RelativeLayoutOnce, "relative-layout-once", "true"),
  V(RelativeCenter, "relative-center", "none"),
  V(EnterTransitionName, "enter-transition-name", ""),
  V(ExitTransitionName, "exit-transition-name", ""),
  V(PauseTransitionName, "pause-transition-name", ""),
  V(ResumeTransitionName, "resume-transition-name", ""),
  V(FlexFlow, "flex-flow", "row nowrap"),
  V(ZIndex, "z-index", "0"),
  V(TextDecorationColor, "text-decoration-color", "black"),
  V(LinearCrossGravity, "linear-cross-gravity", "none"),
  V(MarginInlineStart, "margin-inline-start", "0px"),
  V(MarginInlineEnd, "margin-inline-end", "0px"),
  V(PaddingInlineStart, "padding-inline-start", "0px"),
  V(PaddingInlineEnd, "padding-inline-end", "0px"),
  V(BorderInlineStartColor, "border-inline-start-color", "black"),
  V(BorderInlineEndColor, "border-inline-end-color", "black"),
  V(BorderInlineStartWidth, "border-inline-start-width", "0px"),
  V(BorderInlineEndWidth, "border-inline-end-width", "0px"),
  V(BorderInlineStartStyle, "border-inline-start-style", ""),
  V(BorderInlineEndStyle, "border-inline-end-style", ""),
  V(BorderStartStartRadius, "border-start-start-radius", "0px"),
  V(BorderEndStartRadius, "border-end-start-radius", "0px"),
  V(BorderStartEndRadius, "border-start-end-radius", "0px"),
  V(BorderEndEndRadius, "border-end-end-radius", "0px"),
  V(
    RelativeAlignInlineStart,
    "relative-align-inline-start",
    "-1"
  ),
  V(RelativeAlignInlineEnd, "relative-align-inline-end", "-1"),
  V(RelativeInlineStartOf, "relative-inline-start-of", "-1"),
  V(RelativeInlineEndOf, "relative-inline-end-of", "-1"),
  V(InsetInlineStart, "inset-inline-start", "0px"),
  V(InsetInlineEnd, "inset-inline-end", "0px"),
  V(MaskImage, "mask-image", ""),
  V(GridTemplateColumns, "grid-template-columns", ""),
  V(GridTemplateRows, "grid-template-rows", ""),
  V(GridAutoColumns, "grid-auto-columns", ""),
  V(GridAutoRows, "grid-auto-rows", ""),
  V(GridColumnSpan, "grid-column-span", ""),
  V(GridRowSpan, "grid-row-span", ""),
  V(GridColumnStart, "grid-column-start", ""),
  V(GridColumnEnd, "grid-column-end", ""),
  V(GridRowStart, "grid-row-start", ""),
  V(GridRowEnd, "grid-row-end", ""),
  V(GridColumnGap, "grid-column-gap", ""),
  V(GridRowGap, "grid-row-gap", ""),
  V(JustifyItems, "justify-items", "stretch"),
  V(JustifySelf, "justify-self", "auto"),
  V(GridAutoFlow, "grid-auto-flow", "row"),
  V(Filter, "filter", ""),
  V(ListMainAxisGap, "list-main-axis-gap", "0px"),
  V(ListCrossAxisGap, "list-cross-axis-gap", "0px"),
  V(LinearDirection, "linear-direction", "column"),
  V(Perspective, "perspective", "none"),
  V(Cursor, "cursor", "default"),
  V(TextIndent, "text-indent", "0px"),
  V(ClipPath, "clip-path", ""),
  V(TextStroke, "text-stroke", "0px transparent"),
  V(TextStrokeWidth, "text-stroke-width", "0px"),
  V(TextStrokeColor, "text-stroke-color", "transparent"),
  V(XAutoFontSize, "-x-auto-font-size", "false"),
  V(
    XAutoFontSizePresetSizes,
    "-x-auto-font-size-preset-sizes",
    ""
  ),
  V(Mask, "mask", ""),
  V(MaskRepeat, "mask-repeat", ""),
  V(MaskPosition, "mask-position", ""),
  V(MaskClip, "mask-clip", ""),
  V(MaskOrigin, "mask-origin", ""),
  V(MaskSize, "mask-size", ""),
  V(Gap, "gap", "0px"),
  V(ColumnGap, "column-gap", "0px"),
  V(RowGap, "row-gap", "0px"),
  V(ImageRendering, "image-rendering", "auto"),
  V(Hyphens, "hyphens", "manual"),
  V(XAppRegion, "-x-app-region", "none"),
  V(
    XAnimationColorInterpolation,
    "-x-animation-color-interpolation",
    "auto"
  ),
  V(XHandleCor, "-x-handle-color", "transparent"),
  V(XHandleSize, "-x-handle-size", "0px"),
  V(OffsetPath, "offset-path", ""),
  V(OffsetDistance, "offset-distance", "0%")
);

// In simple styling, only longhand properties are supported.
// TODO: remove this after https://github.com/lynx-family/lynx/pull/1190 is published
pub static LONGHAND_CSS_PROPERTIES: &[&str] = &[
  "top",
  "border-top-color",
  "background-origin",
  "background-repeat",
  "background-size",
  "visibility",
  "border-bottom-color",
  "transition-property",
  "transition-duration",
  "transition-delay",
  "transition-timing-function",
  "content",
  "border-left-style",
  "border-right-style",
  "border-top-style",
  "border-bottom-style",
  "implicit-animation",
  "overflow-x",
  "overflow-y",
  "word-break",
  "background-clip",
  "outline-color",
  "outline-style",
  "outline-width",
  "vertical-align",
  "caret-color",
  "border-top-left-radius",
  "direction",
  "relative-id",
  "relative-align-top",
  "relative-align-right",
  "relative-align-bottom",
  "relative-align-left",
  "relative-top-of",
  "relative-right-of",
  "relative-bottom-of",
  "relative-left-of",
  "border-bottom-left-radius",
  "relative-layout-once",
  "relative-center",
  "enter-transition-name",
  "exit-transition-name",
  "pause-transition-name",
  "resume-transition-name",
  "z-index",
  "text-decoration-color",
  "linear-cross-gravity",
  "border-top-right-radius",
  "margin-inline-start",
  "margin-inline-end",
  "padding-inline-start",
  "padding-inline-end",
  "border-inline-start-color",
  "border-inline-end-color",
  "border-inline-start-width",
  "border-inline-end-width",
  "border-inline-start-style",
  "border-inline-end-style",
  "border-bottom-right-radius",
  "border-start-start-radius",
  "border-end-start-radius",
  "border-start-end-radius",
  "border-end-end-radius",
  "relative-align-inline-start",
  "relative-align-inline-end",
  "relative-inline-start-of",
  "relative-inline-end-of",
  "inset-inline-start",
  "inset-inline-end",
  "mask-image",
  "grid-template-columns",
  "grid-template-rows",
  "grid-auto-columns",
  "grid-auto-rows",
  "grid-column-span",
  "grid-row-span",
  "grid-column-start",
  "grid-column-end",
  "grid-row-start",
  "border-left-width",
  "grid-row-end",
  "grid-column-gap",
  "grid-row-gap",
  "justify-items",
  "justify-self",
  "grid-auto-flow",
  "filter",
  "list-main-axis-gap",
  "list-cross-axis-gap",
  "linear-direction",
  "border-right-width",
  "perspective",
  "cursor",
  "text-indent",
  "clip-path",
  "text-stroke",
  "text-stroke-width",
  "text-stroke-color",
  "-x-auto-font-size",
  "-x-auto-font-size-preset-sizes",
  "left",
  "border-top-width",
  "mask-repeat",
  "mask-position",
  "mask-clip",
  "mask-origin",
  "mask-size",
  "column-gap",
  "row-gap",
  "image-rendering",
  "hyphens",
  "border-bottom-width",
  "-x-app-region",
  "-x-animation-color-interpolation",
  "-x-handle-size",
  "-x-handle-color",
  "offset-distance",
  "offset-path",
  "offset-rotate",
  "color",
  "opacity",
  "display",
  "height",
  "width",
  "max-width",
  "min-width",
  "right",
  "max-height",
  "min-height",
  "padding-left",
  "padding-right",
  "padding-top",
  "padding-bottom",
  "margin-left",
  "margin-right",
  "bottom",
  "margin-top",
  "margin-bottom",
  "letter-spacing",
  "text-align",
  "line-height",
  "text-overflow",
  "font-size",
  "font-weight",
  "position",
  "flex-grow",
  "flex-shrink",
  "flex-basis",
  "flex-direction",
  "flex-wrap",
  "align-items",
  "align-self",
  "align-content",
  "justify-content",
  "box-sizing",
  "font-family",
  "font-style",
  "transform",
  "animation-name",
  "animation-duration",
  "animation-timing-function",
  "animation-delay",
  "animation-iteration-count",
  "background-color",
  "animation-direction",
  "animation-fill-mode",
  "animation-play-state",
  "line-spacing",
  "order",
  "box-shadow",
  "transform-origin",
  "linear-orientation",
  "linear-weight-sum",
  "border-left-color",
  "linear-weight",
  "linear-gravity",
  "linear-layout-gravity",
  "layout-animation-create-duration",
  "layout-animation-create-timing-function",
  "layout-animation-create-delay",
  "layout-animation-create-property",
  "layout-animation-delete-duration",
  "layout-animation-delete-timing-function",
  "layout-animation-delete-delay",
  "border-right-color",
  "layout-animation-delete-property",
  "layout-animation-update-duration",
  "layout-animation-update-timing-function",
  "layout-animation-update-delay",
  "adapt-font-size",
  "aspect-ratio",
  "text-shadow",
  "background-image",
];

#[test]
fn test_parse_css_property_map() {
  let m = get_css_property_map();
  println!("{:?}", m);
}
