packages:
  - benchmark/react
  - examples/*
  - packages/background-only
  - packages/lynx/*
  - packages/react
  - packages/react/refresh
  - packages/react/runtime
  - packages/react/testing-library
  - packages/react/transform
  - packages/react/worklet-runtime
  - packages/rspeedy/*
  - packages/testing-library/*
  - packages/testing-library/examples/*
  - packages/third-party/*
  - packages/tools/*
  - packages/use-sync-external-store
  - packages/web-platform/*
  - packages/webpack/*
  - website

# From `@pnpm/plugin-better-defaults`
enablePrePostScripts: false
ignorePatchFailures: false
optimisticRepeatInstall: true
resolutionMode: "lowest-direct"

# Default catalogs
catalog:
  "@microsoft/api-extractor": "7.52.13"

catalogs:
  # Rsbuild monorepo packages
  rsbuild:
    "@rsbuild/core": "1.5.4"

  # Rspack monorepo packages
  rspack:
    "@rspack/cli": "1.5.2"
    "@rspack/core": "1.5.2"
    "@rspack/test-tools": "1.5.2"

overrides:
  "@rspack/core": "$@rspack/core"
  "@rsbuild/core>@rspack/core": "$@rspack/core"

patchedDependencies:
  "@napi-rs/cli@2.18.4": "patches/@napi-rs__cli@2.18.4.patch"
  "@rollup/plugin-typescript": "patches/@rollup__plugin-typescript.patch"

strictDepBuilds: true

onlyBuiltDependencies:
  - dprint
  - esbuild

ignoredBuiltDependencies:
  - "@biomejs/biome"
  - "@parcel/watcher"
  - "@swc/core"
  - core-js
  - unrs-resolver
