// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

/**
 * Representative Tailwind CSS v3 utility classes, organized using the
 * documentation sidebar taxonomy. Keep each class literal in this file so the
 * Tailwind CLI content scanner can discover it.
 */
export const layoutClasses: readonly string[] = [
  'aspect-square',
  'aspect-video',
  'box-border',
  'box-content',
  'flex',
  'grid',
  'hidden',
  'display-relative',
  'linear',
  'fixed',
  'absolute',
  'relative',
  'sticky',
  'overflow-hidden',
  'overflow-visible',
  'overflow-x-hidden',
  'overflow-x-visible',
  'overflow-y-hidden',
  'overflow-y-visible',
  'inset-1',
  '-inset-1',
  'inset-x-2',
  'inset-y-3',
  'top-4',
  'right-4',
  'bottom-4',
  'left-4',
  'start-4',
  'end-4',
  'visible',
  'invisible',
  'z-10',
  '-z-10',
];

export const flexboxAndGridClasses: readonly string[] = [
  'basis-1/2',
  'flex-row',
  'flex-row-reverse',
  'flex-col',
  'flex-col-reverse',
  'flex-wrap',
  'flex-wrap-reverse',
  'flex-nowrap',
  'flex-1',
  'flex-auto',
  'flex-initial',
  'flex-none',
  'grow',
  'grow-0',
  'shrink',
  'shrink-0',
  'order-1',
  '-order-1',
  'grid-cols-2',
  'col-auto',
  'col-span-2',
  'col-start-2',
  '-col-start-2',
  'col-end-3',
  'grid-rows-2',
  'row-auto',
  'row-span-2',
  'row-start-2',
  '-row-start-2',
  'row-end-3',
  'grid-flow-row',
  'auto-cols-auto',
  'auto-cols-max',
  'auto-cols-fr',
  'auto-rows-auto',
  'auto-rows-max',
  'auto-rows-fr',
  'gap-4',
  'gap-x-2',
  'gap-y-2',
  'items-stretch',
  'items-start',
  'items-center',
  'items-end',
  'items-baseline',
  'self-auto',
  'self-start',
  'self-center',
  'self-end',
  'self-stretch',
  'self-baseline',
  'content-start',
  'content-center',
  'content-end',
  'content-between',
  'content-around',
  'content-stretch',
  'justify-start',
  'justify-center',
  'justify-end',
  'justify-between',
  'justify-around',
  'justify-evenly',
  'justify-stretch',
  'justify-items-start',
  'justify-items-center',
  'justify-items-end',
  'justify-items-stretch',
  'justify-self-auto',
  'justify-self-start',
  'justify-self-center',
  'justify-self-end',
  'justify-self-stretch',
];

export const spacingClasses: readonly string[] = [
  'p-4',
  'px-4',
  'py-4',
  'ps-4',
  'pe-4',
  'm-4',
  '-m-4',
  'mx-4',
  'my-4',
  'ms-4',
  'me-4',
];

export const sizingClasses: readonly string[] = [
  'w-4',
  'min-w-0',
  'max-w-full',
  'h-4',
  'min-h-0',
  'max-h-full',
  'size-4',
];

export const typographyClasses: readonly string[] = [
  'font-sans',
  'text-base',
  'italic',
  'not-italic',
  'font-normal',
  'font-bold',
  'tracking-wide',
  '-tracking-wide',
  'leading-6',
  'text-left',
  'text-center',
  'text-right',
  'text-start',
  'text-end',
  'text-red-500',
  'text-red-500/50',
  'underline',
  'line-through',
  'no-underline',
  'text-ellipsis',
  'text-clip',
  'indent-4',
  '-indent-4',
  'align-middle',
  'break-normal',
  'break-all',
  'truncate',
  'whitespace-normal',
  'whitespace-nowrap',
];

export const backgroundClasses: readonly string[] = [
  'bg-clip-border',
  'bg-clip-padding',
  'bg-clip-content',
  'bg-red-500',
  'bg-red-500/50',
  'bg-origin-padding',
  'bg-center',
  'bg-no-repeat',
  'bg-cover',
  'bg-none',
  'bg-[linear-gradient(red,blue)]',
];

export const borderClasses: readonly string[] = [
  'rounded',
  'rounded-lg',
  'rounded-s-lg',
  'border',
  'border-2',
  'border-x-2',
  'border-s-2',
  'border-red-500',
  'border-red-500/50',
  'border-s-red-500',
  'border-solid',
  'border-dashed',
  'border-dotted',
  'border-double',
  'border-none',
];

export const effectClasses: readonly string[] = [
  'shadow',
  'shadow-sm',
  'shadow-none',
  'shadow-[0_1px_2px_#000]',
  'opacity-50',
];

export const filterClasses: readonly string[] = [
  'blur',
  'blur-sm',
  'grayscale',
  'grayscale-50',
  'grayscale-none',
  'filter-none',
];

export const transitionAndAnimationClasses: readonly string[] = [
  'transition',
  'transition-none',
  'transition-colors',
  'transition-opacity',
  'transition-transform',
  'transition-filter',
  'duration-150',
  'ease-in-out',
  'delay-75',
  'animate-spin',
];

export const transformClasses: readonly string[] = [
  'scale-95',
  'scale-x-95',
  '-scale-y-95',
  'rotate-45',
  'rotate-x-45',
  'rotate-y-45',
  'rotate-z-45',
  '-rotate-45',
  'translate-x-4',
  'translate-y-4',
  'translate-z-4',
  '-translate-x-4',
  'skew-x-3',
  'skew-y-3',
  'skew-x-12',
  'skew-y-6',
  '-skew-x-3',
  'transform',
  'transform-cpu',
  'transform-gpu',
  'transform-none',
  'transform-[translateX(20px)_rotate(10deg)]',
  'origin-center',
];

export const interactivityClasses: readonly string[] = [
  'caret-red-500',
  'caret-red-500/50',
];

export const presetExtensionClasses: readonly string[] = [
  'normal',
  'ltr',
  'rtl',
  'lynx-rtl',
  'perspective-normal',
  'solo-translate-x-4',
  'solo-rotate-45',
  'solo-scale-95',
  'solo-skew-x-3',
];

export const uiVariantClasses: readonly string[] = [
  'ui-open:bg-red-500',
  'group-ui-open:bg-blue-500',
  'peer-ui-checked:text-red-500',
  'parent-ui-open:opacity-50',
];

/**
 * Unsupported Tailwind candidates that must remain visible to the content
 * scanner so the integration test can assert that the preset emits no selector.
 */
export const unsupportedClasses: readonly string[] = [
  'aspect-auto',
  'block',
  'static',
  'overflow-auto',
  'collapse',
  'z-auto',
  'grid-cols-none',
  'grid-cols-subgrid',
  'grid-rows-none',
  'grid-rows-subgrid',
  'auto-cols-min',
  'auto-rows-min',
  'justify-normal',
  'content-normal',
  'content-baseline',
  'content-evenly',
  'whitespace-pre',
  'break-words',
  'break-keep',
  'bg-clip-text',
  'brightness-100',
  'contrast-100',
  'saturate-100',
  'place-content-center',
  'place-items-center',
  'place-self-center',
];

export const testClasses: string = [
  ...layoutClasses,
  ...flexboxAndGridClasses,
  ...spacingClasses,
  ...sizingClasses,
  ...typographyClasses,
  ...backgroundClasses,
  ...borderClasses,
  ...effectClasses,
  ...filterClasses,
  ...transitionAndAnimationClasses,
  ...transformClasses,
  ...interactivityClasses,
  ...presetExtensionClasses,
  ...uiVariantClasses,
].join(' ');
