import * as ReactLynx from "@lynx-js/react/internal";
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c)=><view>{__c}</view>, <Component/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c)=><view>{__c}</view>, <Component/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c)=><view id="1" exposure-screen-margin-top>{__c}</view>, <Component/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c)=><view bindtap={()=>{}} id="1">{__c}</view>, <Component/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c)=><view ui:bindtap={()=>{}} id="1">{__c}</view>, <Component/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c)=><view>{__c}</view>, <Component key="222"/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c)=><view style={s}>{__c}</view>, <Component key="222"/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c, __spread)=><view {...__spread}>{__c}</view>, <Component {...props} key="222"/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c, __spread)=><view {...__spread}>{__c}</view>, <Component {...props} key="222" id="!!!" className="!!!!"/>);
<Component {...props} key="222" id="!!!" className="!!!!"/>;
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c, __spread)=><view {...__spread}>{__c}</view>, <Component {...props} key="222" id="!!!" className="!!!!" someProps={p}/>);
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c, __spread)=><view {...__spread}>{__c}</view>, <Component {...props} key="222" id="!!!" className="!!!!" style={s}/>);
<Component/>;
/*#__PURE__*/ ReactLynx.wrapWithLynxComponent((__c)=><view>{__c}</view>, <Component/>);
<Component/>;
